### ISSUE TITLE
AWS Security Network

### ISSUE THREAD

**Issue by Cu4rach4** [abernix/meteord#13]
Could you add a new settings on docker image?

The problem is when try to settings a security group on AWS with filter by another security group or internal IP (Docker start with 172.17.0.1).

So you cant reach that network, and  error "502 Bad gateway" appears, so i think we can add a new field on docker settings like:

```
docker{
 image:'',
 imageport: ,
 bridgeLan: ''
}
```

So bridgeLan set --bip: IP on docker run.

Hope you can understand my bad english.

Thanks.

**Comment by zodern** [comment]
This looks more like an issue with [meteor-up](https://github.com/zodern/meteor-up).

**Comment by Cu4rach4** [comment]
Yeap, closed and open on meteor-up?

**Comment by zodern** [comment]
Yes
