### ISSUE TITLE
Upgrading Node and npm?

### ISSUE THREAD

**Issue by dominicarrojado** [abernix/meteord#14]
Hi, I'm getting an error in deploying the app (using MUP) with a Meteor version 1.5. Would you upgrade the docker image soon?

**Comment by abernix** [comment]
What's the error?

**Comment by lukaszzattoo** [comment]
Hi,

I would like to know how I can update Node version from 4.8.0 to at least 5.7.1? Is that possible?

**Comment by wlodi83** [comment]
Hi @abernix, I have similar question:

I would like to know how I can update Node version from 4.8.0 to at least 5.7.1 in meteord? Is that possible?

**Comment by abernix** [comment]
You should not use Meteor with Node 5.7.1.

Node 4.8.4 is available now via the default `latest` tag for this repo and should work fine with Meteor 1.5.  If you have an actual error next time, please include it.  See [other tags available here](https://hub.docker.com/r/abernix/meteord/tags/).
