### ISSUE TITLE
Thank you very much for delivering us this working version of meteord

### ISSUE THREAD

**Issue by pozylon** [abernix/meteord#2]

**Comment by abernix** [comment]
You're welcome.  It's probably broken for Meteor 1.4.2 right now, but I have a solution coming for that soon. 😸

**Comment by Netherdrake** [comment]
@abernix how soon?

I need to deploy something for the client and their live demo on a conference today.

Any ideas how to workaround:

```
=> Executing Meteor Build...

You are attempting to run Meteor as the "root" user. If you are developing,
this is almost certainly *not* what you want to do and will likely result in
incorrect file permissions. However, if you are running this in a build process
(CI, etc.) or you are absolutely sure you know what you are doing, add the
`--unsafe-perm` flag to this command to proceed.

The command '/bin/sh -c bash $METEORD_DIR/on_build.sh' returned a non-zero code: 1
```

**Comment by chitezh** [comment]
@Netherdrake 
Here is a workaround bit that would require that you make a fork of this repo and make the necessary changes.

https://github.com/meteor/meteor/issues/7959#issuecomment-256297015

**Comment by abernix** [comment]
@Neitherdrake For the `:onbuild` image, I'm recommending https://github.com/jshimko/meteor-launchpad, at least for the time-being.  I have another update coming soon but I like what's going on over there.
