### ISSUE TITLE
Support for Meteor 1.6?

### ISSUE THREAD

**Issue by lhz516** [abernix/meteord#20]
I know Meteor 1.6 is currently in Beta, but it would be great if you can release an image tag for nodejs 8.3.0 so that we can deploy Meteor 1.6 project to the server.

**Comment by abernix** [comment]
I like your ambition!  Done! :smile:

See all available tags here: https://hub.docker.com/r/abernix/meteord/tags/

Remember: I would consider both Node 8.3.0 and Meteor 1.6 beta for the next month or so, but please do help test! :)

**Comment by jamesgibson14** [comment]
Can we get a node 8.7.0 tag.
