### ISSUE TITLE
How to enable DDP Connections?

### ISSUE THREAD

**Issue by enzolutions** [abernix/meteord#22]
Hi @abernix 

I am using this image through the project http://meteor-up.com/ and works perfectly.

The only thing I am missing now is how to enable DDP connection from external applications using DDP Clients.

Any recommendation?

**Comment by abernix** [comment]
DDP connections should work just fine.  It's certainly not something that's controlled by this image, so if it's not working, your problem lies elsewhere (likely your proxy server).
