### ISSUE TITLE
patch for segmentation faults?

### ISSUE THREAD

**Issue by sirpy** [abernix/meteord#23]
Does the latest 4.8.4 include the patch you did for segfaults?
Because i seem to get segfaults on production via docker but recently i tried running the code with 
"meteor(1.5.2.2) node main.js" and it seems to have stopped the segfaults

**Comment by abernix** [comment]
It doesn't, currently.  Though Node 4.8.6 will be coming out on Tuesday next week and I'll build that.

**Comment by abernix** [comment]
I should have added that Node 4.8.6 is expected to include my fix. :smile:

**Comment by abernix** [comment]
4.8.6 came out yesterday and did officially include my fix.  I released a `meteord` for it.  See [the Docker Hub readme](https://hub.docker.com/r/abernix/meteord/) for details!
