### ISSUE TITLE
Node version issue using MUP

### ISSUE THREAD

**Issue by piggydoughnut** [abernix/meteord#24]
Hello)

I am using your abernix/meteord:base Docker image in MUP. 
I can see in the Dockerfile here that the node version is 4.8.4, but every time I deploy the node version is 4.8.3 for some reason. I connect to my server and go into the docker instance and run node --version and I get 4.8.3.

Any thoughts on what am I doing wrong? 

mup config file
`
    docker: {
      image: 'abernix/meteord:base',
    }
`

Thanks a lot, any help is appreciated :D Lovely day to you <3

**Comment by abernix** [comment]
Please try again.  I think the `base` tag was still pointing to `node-4.8.3-base` instead of `node-4.8.4-base` as it was supposed to.  Sorry that happened!  If it still happens, I'm happy to reopen and investigate more.
