### ISSUE TITLE
node update for 1.6 in latest tag

### ISSUE THREAD

**Issue by s7dhansh** [abernix/meteord#25]
Can you kindly update the latest with node 8? We are still using specific version tags.

**Comment by abernix** [comment]
Done.  Please see the updated [Docker Hub Readme](https://hub.docker.com/r/abernix/meteord/) for the tag variations and explanations and see the [tag list](https://hub.docker.com/r/abernix/meteord/tags/) for the complete set of options.

Note, that while Meteor 1.6 uses Node 8.8.1 as that that was the version available when it was released, I skipped straight to 8.9.0.  It will work just fine and there are no breaking changes between those versions.
