### ISSUE TITLE
You are attempting to run Meteor as the "root" user

### ISSUE THREAD

**Issue by chitezh** [abernix/meteord#3]
You are attempting to run Meteor as the "root" user. If you are developing,
this is almost certainly _not_ what you want to do and will likely result in
incorrect file permissions. However, if you are running this in a build process
(CI, etc.) or you are absolutely sure you know what you are doing, add the
`--unsafe-perm` flag to this command to proceed.

Kindly add the USER to dockerfile.

Thanks

**Comment by abernix** [comment]
I do believe that the correct solution is to stop using the root user in the Docker image for a variety of reasons.  In fact, it's very similar to what has been wisely done with another Docker image project/fork which I've just recently found: https://github.com/jshimko/meteor-launchpad

I'd recommend trying it out and see if it works for you because this fork of mine was only meant to be a short-term solution.

**Comment by 0o-de-lally** [comment]
+1  I tried to re-build an image that was working two days ago (no changes to docker nor code), and I get the same result. Error msg below.

@abernix  thanks for pointing out meteor-launchpad. @stubailo Sudden failures like this remind me it would be nice to have an MDG recommended/reference image. 

```
You are attempting to run Meteor as the "root" user. If you are developing, this is almost certainly *not* what you want to do and will likely result in incorrect file permissions. However, if you are running this in a build process (CI, etc.) or you are absolutely sure you know what you are doing, add the `--unsafe-perm` flag to this command to proceed.

A build step failed: The command '/bin/sh -c bash $METEORD_DIR/on_build.sh' returned a non-zero code: 1
```

**Comment by abernix** [comment]
@keyscores and @chitezh Are you using the `:onbuild` image or the `:base` image?

**Comment by 0o-de-lally** [comment]
FROM abernix/meteord:onbuild

**Comment by abernix** [comment]
Ok, so this problem can be easily fixed but it's reliant on Meteor 1.4.2.1 getting released which will have a fix for meteor/meteor#7959.  Otherwise, things get a lot more complex and hack-y.

**Comment by 0o-de-lally** [comment]
The mystery to me is that error appeared without I ever upgrading or changing code. Literally, I ran a build from the same git commit on two separate days, and the second one failed. Why would that be?

**Comment by abernix** [comment]
This Docker image (like all of its counterparts) simply downloads the default Meteor tool from https://install.meteor.com.

Therefore, once Meteor 1.4.2 was released, this became the default install for everyone.  The default Meteor tool then downloads the version of Meteor that your application uses and springboards (passes control) to it.

Unfortunately, a bug in `--unsafe-perm` logic cropped up with that issue which prevented the default Meteor tool from spring-boarding to your version and here we are. :smile:

**Comment by abernix** [comment]
Btw, you could avoid this problem by using the `:base` image which doesn't do the actual build inside the Docker, but instead requires you run it on your local machine.  You could therefore:
- Run `meteor build` on your own computer, without root: `meteor build --architecture=os.linux.x86_64 ../output_build_directory_used_below`
- Then run the docker this way:
  
  ```
  docker run -d \
  -e ROOT_URL=http://yourapp.com \
  -e MONGO_URL=mongodb://url \
  -e MONGO_OPLOG_URL=mongodb://oplog_url \
  -v /bundle_directory_produced_by_meteor_build_above:/bundle \
  -p 8080:80 \
  abernix/meteord:base
  ```

**Comment by 0o-de-lally** [comment]
I see, thanks for the explanation. Would it be worth incorporating the changes in meteor-launchpad to abernix/meteord?

How would I use meteord:base with dockerhub or quayio automated builds?

**Comment by chitezh** [comment]
I am using  :onbuild as part of a CI stage in Circleci

**Comment by chitezh** [comment]
https://github.com/jshimko/meteor-launchpad worked for me. Thanks
