### ISSUE TITLE
Get security fixes in regularly

### ISSUE THREAD

**Issue by albuch** [abernix/meteord#32]
To get all Debian security fixes in more frequently an automated build could be set up in Docker Hub listening on upstream repository changes via Repository links.
https://docs.docker.com/docker-hub/builds/#repository-links

If corresponding Debian image changes the meteord image could be rebuilt and re-published under the same tag.

Currently the Debian base image has several critical security issues that have fixes available.

**Comment by abernix** [comment]
If you're willing to take a shot at doing this, that'd be great and a PR would be welcome!  As it stands right now, the builds are automatic when pushed to CircleCI with the appropriate branch.

If you're unable, I'll keep doing them manually as I have time and with the Node.js security releases as guidance and if anyone pings me with anything critical.
