### ISSUE TITLE
Specify node-args for (build) process

### ISSUE THREAD

**Issue by smeijer** [abernix/meteord#35]
I'm getting the error below on while building the container. Would be helpfull if we could specify `node-args` to the build process, and perhaps the running node process as well.

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

`--node-args="--max-old-space-size=6144"` is expected to fix this error.

**Comment by abernix** [comment]
This should have been fixed as of #15, though I'll note that I believe you can just set that flag using the `NODE_OPTIONS` environment variable even without that fix, as noted [in the Node.js documentation](https://nodejs.org/api/cli.html#cli_node_options_options).
