### ISSUE TITLE
Need new NodeJS version for Meteor 1.6.1

### ISSUE THREAD

**Issue by sjkdev21** [abernix/meteord#36]
I was wondering if you had any plan to bump the NodeJS version to the custom v8.11.1 that the Meteor team build https://github.com/meteor/node/commits/v8.11.1-meteor.  This would ensure the smooth running of the current latest version of Meteor.

**Comment by lc3t35** [comment]
+1

**Comment by WayneUong** [comment]
@abernix Please

**Comment by abernix** [comment]
Done with #37!
