### ISSUE TITLE
xhr polling with abernix/meteord:onbuild

### ISSUE THREAD

**Issue by WayneUong** [abernix/meteord#40]
When I use `abernix/meteord:onbuild` to deploy. The meteor uses xhr polling instead of ddp and it's very slow. Is there a reason for this? App functions normally when deployed with mup and `abernix/meteord:base`.

<img width="816" alt="screen shot 2018-06-29 at 10 58 25 am" src="https://user-images.githubusercontent.com/8436742/42107313-b8c81c3a-7b8b-11e8-9901-e5e3852ac74c.png">

**Comment by abernix** [comment]
This isn't because of `abernix/meteord:onbuild`, more than likely it's because you have a proxy in front of the server which doesn't support WebSockets!
