### ISSUE TITLE
Dependency issue  -  Removal of Wheezy and Jessie from mirrors

### ISSUE THREAD

**Issue by metju90** [abernix/meteord#47]
I am facing the following issue

```
W: Failed to fetch
http://ftp.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages
404  Not Found

W: Failed to fetch
http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages
 404  Not Found
```

Quoting [this link](https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html)

>as Wheezy and Jessie have been integrated into the archive.debian.org
structure recently, we are now removing all of Wheezy and all non-LTS
architectures of Jessie from the mirror network starting today.
That is, only Jessie i386, amd64, armel and armhf will continue to be
hosted on the normal mirrors.

>The data is, of course, not lost - the whole of it is synced
to archive.debian.org, so if you still need it you will be able to get
it from there.[1]

**Comment by metju90** [comment]
PR [#46](https://github.com/abernix/meteord/pull/46) should fix this problem

**Comment by enzolutions** [comment]
Hello, guys any plans to apply this to the next release?

**Comment by abernix** [comment]
Fixed in the most recently published image.  Per my comment in https://github.com/abernix/meteord/pull/46#issuecomment-481260518, this was not done through doing a major version upgrade — just a simple re-build of the existing image.
