### ISSUE TITLE
Update for Meteor 1.11

### ISSUE THREAD

**Issue by mwarren2** [abernix/meteord#54]
Hi, any chance of an update to Node 12.18.3? Thanks

**Comment by emjimadhu** [comment]
I have created docker images for our project. 

[https://hub.docker.com/repository/docker/emjimadhu/meteord/tags?page=1](https://hub.docker.com/repository/docker/emjimadhu/meteord/tags?page=1)

Until he updates his docker. You can use mine.

**Comment by eugle** [comment]
@emjimadhu Thank you for your

**Comment by abernix** [comment]
I've published new images with Node.js 12.20.0 and Meteor 1.12.
