### ISSUE TITLE
Bcrypt issue

### ISSUE THREAD

**Issue by JulianKingman** [abernix/meteord#8]
Hey, I'm having the issue described in this issue: https://github.com/kadirahq/meteor-up/issues/267

Basically, problems with bcrypt. I'm using Meteor 1.4.2, I think, I'll double-check tomorrow. Just wanted to see if you knew how to deal with this.

**Comment by crstn210** [comment]
any update here?

**Comment by abernix** [comment]
What version of Meteor are you using?  You should use the latest!

**Comment by janzheng** [comment]
using the latest Meteor, and Zodern still seems to have problems

**Comment by abernix** [comment]
Unfortunately, I don't have an answer for you as this is not typical.  A reliable reproduction would be the only way to work on this – and I'd that would have to be quite a comprehensive reproduction as it looks like `npm install` is getting `Killed` by the kernel, so I'd encourage you to consider the environment and version of Docker you're encountering the error in.  I'm not sure there is much to fix from the Docker image (this repo) side of things.
