### ISSUE TITLE
[Help] How to specify node version

### ISSUE THREAD

**Issue by s7dhansh** [abernix/meteord#9]
When using this image with mup, I am trying to specify node version 4.6.2, using 
```
docker: {
			image: 'abernix/meteord:base', //optional
			args: ['-v /etc/timezone:/etc/timezone', '-v /etc/localtime:/etc/localtime', '--build-arg NODE_VERSION=4.6.2']
		},
```

It fails with the error : `unknown flag: --build-arg`

What is the proper procedure?

EDIT: Why 4.6.2? Because Node 4.7+ is causing distinct memory and cpu overuse.

**Comment by s7dhansh** [comment]
On reading further I assume that I have to build a new image entirely from this repo using build-arg? Is there any simpler way?

**Comment by abernix** [comment]
The Node version is baked in, however you can use whichever previous tag you'd like from [this list of tags](https://hub.docker.com/r/abernix/meteord/tags/).   Remember to consider Node Security issues when using an older version though.
